Repository kammt/MemeAssembly, pull requests merged in 2021-04, with the labels that each got.

#14 New Command: "what can I say except c"
  README.md
  compiler/translator.c
  examples/alphabet.memeasm
  examples/the-link.memeasm
Labels: enhancement, new-command

#15 Fixed rand() always returning the same value
  .idea/.gitignore
  .idea/misc.xml
  .idea/vcs.xml
  compiler/preprocessor.c
Labels: bug

#19 New commands for doubling and halving values
  README.md
  compiler/translator.c
Labels: enhancement, new command
